import { spawn } from "child_process";
import { promises as fs } from "fs";
import path from "path";
import { readImportBuffer, saveImportFile } from "@/lib/import/storage";
import { setLatestPptExport } from "./pptMeta";
import {
  PPT_CANVAS,
  type PptCanvasFormat,
  pythonBinary,
  resolvePptMasterScriptsDir,
  resolvePptWorkspaceDir,
} from "./pptMasterPaths";
import { buildSlideSvg, type PptGenerationPlan } from "./slideSvgBuilder";

export type PptEngineStatus = {
  available: boolean;
  scriptsPath: string;
  error?: string;
};

export type PptGenerateResult = {
  storagePath: string;
  fileName: string;
  slideCount: number;
  projectPath: string;
  plan: PptGenerationPlan;
};

async function runPython(args: string[], cwd?: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const proc = spawn(pythonBinary(), args, {
      cwd,
      windowsHide: true,
      stdio: ["ignore", "pipe", "pipe"],
    });
    let stdout = "";
    let stderr = "";
    proc.stdout.setEncoding("utf8");
    proc.stderr.setEncoding("utf8");
    proc.stdout.on("data", (c: string) => {
      stdout += c;
    });
    proc.stderr.on("data", (c: string) => {
      stderr += c;
    });
    proc.on("error", reject);
    proc.on("close", (code) => {
      if (code !== 0) reject(new Error(stderr.trim() || stdout.trim() || `python exit ${code}`));
      else resolve(stdout);
    });
  });
}

export async function getPptEngineStatus(): Promise<PptEngineStatus> {
  const scriptsPath = resolvePptMasterScriptsDir();
  try {
    await fs.access(path.join(scriptsPath, "svg_to_pptx.py"));
    await runPython(["-c", "import pptx; print('ok')"]);
    return { available: true, scriptsPath };
  } catch (error) {
    return {
      available: false,
      scriptsPath,
      error:
        error instanceof Error
          ? error.message
          : "PPT Master 미설치 — npm run setup:ppt-master && pip install -r requirements-ppt-master.txt",
    };
  }
}

async function initProject(
  bookId: string,
  format: PptCanvasFormat,
): Promise<string> {
  const scripts = resolvePptMasterScriptsDir();
  const workspace = resolvePptWorkspaceDir(bookId);
  await fs.mkdir(workspace, { recursive: true });
  const projectName = `book_${bookId.slice(0, 8)}`;
  const manager = path.join(scripts, "project_manager.py");
  await runPython([manager, "init", projectName, "--format", format, "--dir", workspace]);
  const entries = await fs.readdir(workspace, { withFileTypes: true });
  const dir = entries.find((e) => e.isDirectory() && e.name.includes(projectName));
  if (!dir) throw new Error("PPT 프로젝트 초기화 실패");
  return path.join(workspace, dir.name);
}

export async function generatePptxFromPlan(
  bookId: string,
  plan: PptGenerationPlan,
  format: PptCanvasFormat = "ppt169",
): Promise<PptGenerateResult> {
  const status = await getPptEngineStatus();
  if (!status.available) throw new Error(status.error ?? "PPT 엔진을 사용할 수 없습니다.");

  const scripts = resolvePptMasterScriptsDir();
  const projectPath = await initProject(bookId, format);
  const svgDir = path.join(projectPath, "svg_final");
  await fs.mkdir(svgDir, { recursive: true });

  const canvas = PPT_CANVAS[format];
  const slides = plan.slides;
  let idx = 0;
  for (const slide of slides) {
    idx += 1;
    const fileName = `${String(idx).padStart(2, "0")}_${slide.id.replace(/^\d+_/, "")}.svg`;
    const svg = buildSlideSvg(slide, idx - 1, slides.length, canvas.viewBox);
    await fs.writeFile(path.join(svgDir, fileName), svg, "utf-8");
  }

  const designSpec = `# ${plan.deckTitle}\n\nGenerated by LoBooK AI + PPT Master.\n`;
  await fs.writeFile(path.join(projectPath, "design_spec.md"), designSpec, "utf-8");

  const svgToPptx = path.join(scripts, "svg_to_pptx.py");
  const outName = `${plan.deckTitle.replace(/[^\w가-힣.-]+/g, "_").slice(0, 40) || "presentation"}.pptx`;
  const exportsDir = path.join(projectPath, "exports");
  await fs.mkdir(exportsDir, { recursive: true });
  const outPath = path.join(exportsDir, outName);

  await runPython([svgToPptx, projectPath, "-s", "final", "-o", outPath]);

  const buffer = await fs.readFile(outPath);
  const file = new File([buffer], outName, {
    type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  });

  const saved = await saveImportFile(file, bookId, "pptx");
  await setLatestPptExport(bookId, {
    storagePath: saved.storagePath,
    fileName: outName,
    slideCount: slides.length,
    prompt: plan.deckTitle,
  });

  return {
    storagePath: saved.storagePath,
    fileName: outName,
    slideCount: slides.length,
    projectPath,
    plan,
  };
}

export async function readPptxBuffer(storagePath: string): Promise<Buffer> {
  return readImportBuffer(storagePath);
}
